"""Generate an HRSID fine-tuning config for official IDEA-Research DINO."""

from __future__ import annotations

import argparse
import os
from pathlib import Path

from config import DEFAULTS


CONFIG_TEMPLATE = '''# Auto-generated by dino_detector/gen_config.py.
# Based on IDEA-Research/DINO config/DINO/DINO_4scale.py.

_base_ = ['{base_config}']

# HRSID has one semantic class, but its raw COCO category_id is 1. The official
# DINO dataset loader uses category_id as the label index, so index 0 is unused.
num_classes = {num_classes}
dn_labelbook_size = {dn_labelbook_size}

lr = {lr}
lr_backbone = {lr_backbone}
batch_size = {batch_size}
weight_decay = {weight_decay}
epochs = {epochs}
lr_drop = {lr_drop}
save_checkpoint_interval = 1

modelname = 'dino'
backbone = 'resnet50'
num_feature_levels = 4
return_interm_indices = [1, 2, 3]

use_dn = True
dn_number = 100
dn_box_noise_scale = 1.0
dn_label_noise_ratio = 0.5
embed_init_tgt = True

use_ema = False
'''


def write_config(
    output: str,
    dino_repo: str,
    num_classes: int = DEFAULTS["num_classes"],
    dn_labelbook_size: int = DEFAULTS["dn_labelbook_size"],
    epochs: int = DEFAULTS["epochs"],
    batch_size: int = DEFAULTS["batch_size"],
    lr: float = DEFAULTS["lr"],
    lr_backbone: float = DEFAULTS["lr_backbone"],
    weight_decay: float = DEFAULTS["weight_decay"],
) -> str:
    base_config = os.path.join(dino_repo, "config", "DINO", "DINO_4scale.py")
    lr_drop = max(1, epochs - 1)
    text = CONFIG_TEMPLATE.format(
        base_config=base_config,
        num_classes=num_classes,
        dn_labelbook_size=max(dn_labelbook_size, num_classes),
        epochs=epochs,
        batch_size=batch_size,
        lr=lr,
        lr_backbone=lr_backbone,
        weight_decay=weight_decay,
        lr_drop=lr_drop,
    )

    output_path = Path(output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(text)
    print(f"Wrote {output_path}")
    return str(output_path)


def parse_args():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--output", default=DEFAULTS["config_file"])
    p.add_argument("--dino-repo", default=DEFAULTS["dino_repo"])
    p.add_argument("--num-classes", type=int, default=DEFAULTS["num_classes"])
    p.add_argument("--dn-labelbook-size", type=int, default=DEFAULTS["dn_labelbook_size"])
    p.add_argument("--epochs", type=int, default=DEFAULTS["epochs"])
    p.add_argument("--batch-size", type=int, default=DEFAULTS["batch_size"])
    p.add_argument("--lr", type=float, default=DEFAULTS["lr"])
    p.add_argument("--lr-backbone", type=float, default=DEFAULTS["lr_backbone"])
    p.add_argument("--weight-decay", type=float, default=DEFAULTS["weight_decay"])
    return p.parse_args()


def main():
    args = parse_args()
    write_config(
        output=args.output,
        dino_repo=args.dino_repo,
        num_classes=args.num_classes,
        dn_labelbook_size=args.dn_labelbook_size,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        lr_backbone=args.lr_backbone,
        weight_decay=args.weight_decay,
    )


if __name__ == "__main__":
    main()
