import argparse
import re
from pathlib import Path

def patch_input_size(deim_root: str, size: int):
    root = Path(deim_root)
    dl = root / "configs" / "base" / "dataloader.yml"
    txt = dl.read_text()
    txt = re.sub(r"(?m)(\bsize: )\[\d+, \d+\]", rf"\g<1>[{size}, {size}]", txt)
    txt = re.sub(r"(?m)(\bbase_size: )\d+", rf"\g<1>{size}", txt)
    dl.write_text(txt)

    mc = root / "configs" / "base" / "dfine_hgnetv2.yml"
    t2 = mc.read_text()
    t2 = re.sub(r"(?m)(\beval_spatial_size: )\[\d+, \d+\]", rf"\g<1>[{size}, {size}]", t2)
    mc.write_text(t2)
    print(f"Patched input size -> {size}x{size} (dataloader.yml + dfine_hgnetv2.yml)")

def schedule(epochs: int):
    no_aug = max(2, round(epochs * 12 / 132))
    stop = epochs - no_aug
    flat = 4 + (epochs - no_aug) // 2
    return flat, no_aug, stop

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--deim-root", required=True, help="Path to cloned DEIM repo.")
    ap.add_argument("--size", default="s", choices=["n", "s", "m", "l", "x"])
    ap.add_argument("--img-dir", required=True, help="HRSID_JPG/JPEGImages")
    ap.add_argument("--train-json", required=True, help="annotations/train2017.json")
    ap.add_argument("--val-json", required=True, help="annotations/test2017.json")
    ap.add_argument("--epochs", type=int, default=50)
    ap.add_argument("--batch", type=int, default=32, help="train total_batch_size")
    ap.add_argument("--imgsz", type=int, default=640,
                    help="Input resolution (DEIM default 640; 800 = HRSID native).")
    args = ap.parse_args()

    patch_input_size(args.deim_root, args.imgsz)

    flat, no_aug, stop = schedule(args.epochs)

    cfg = f"""# AUTO-GENERATED by gen_config.py — DEIM fine-tune on HRSID
__include__: [
  './deim_hgnetv2_{args.size}_coco.yml',
]

output_dir: ./outputs/deim_hrsid_{args.size}_{args.imgsz}

# HRSID has one category with id=1; remap off uses raw id as label index,
# so num_classes must be 2 (index 0 unused).
num_classes: 2
remap_mscoco_category: False

epoches: {args.epochs}
flat_epoch: {flat}      # warmup(4) + (epochs - no_aug)//2
no_aug_epoch: {no_aug}

train_dataloader:
  dataset:
    img_folder: {args.img_dir}
    ann_file: {args.train_json}
    transforms:
      policy:
        epoch: [4, {flat}, {stop}]
  collate_fn:
    mixup_epochs: [4, {flat}]
    stop_epoch: {stop}
  total_batch_size: {args.batch}

val_dataloader:
  dataset:
    img_folder: {args.img_dir}
    ann_file: {args.val_json}
  total_batch_size: {args.batch * 2}
"""

    out = Path(args.deim_root) / "configs" / "deim_dfine" / f"deim_hrsid_{args.size}.yml"
    out.write_text(cfg)
    print(f"Wrote {out}")
    print(f"  size={args.size}  epochs={args.epochs}  batch={args.batch}")
    print(f"  schedule: flat_epoch={flat}  no_aug_epoch={no_aug}  stop_epoch={stop}")
    print(str(out))                                       

if __name__ == "__main__":
    main()
